services:
  php:
    build: ./docker/php
    container_name: symfony-php
    volumes:
      - ./app:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - db

  nginx:
    image: nginx:1.25-alpine
    container_name: symfony-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mariadb:11
    container_name: symfony-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    container_name: symfony-adminer
    restart: always
    ports:
      - "8081:8080"  # accès sur http://localhost:8081

  mailhog:
    image: mailhog/mailhog
    container_name: symfony-mailhog
    restart: always
    ports:
      - "8025:8025"  # interface web: http://localhost:8025
      - "1025:1025"  # port SMTP
